package frc.robot.subsystems.wrist;

public enum WristState {
    IDLE,
    INVERTED_IDLE,
    PRE_L4,
    L1,
    L2,
    L3,
    L4_TRANSITION,
    CAPPED_L4,
    CORAL_STATION,
    HOME_WRIST,
    L4_WRIST,
    INVERTED_CORAL_STATION,
    DISABLED,
    PRE_ALGAE_SCORE,
    FRONT_ALGAE_SCORE,
    INTAKE_ALGAE,
    GROUND_ALGAE_INTAKE,
    FAILSAFE_GROUND_ALGAE_INTAKE,
    ALGAE_FLICK,
    PROCESSOR,
    SCORE_ALGAE,
    CAGE_FLIP
}
